name: CD - Déploiement GitHub Pages et Runner

on:
  push:
    branches:
      - PRO

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages

  deploy-runner:
    runs-on: self-hosted
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Déploiement sur Nginx
        run: |
          sudo cp index.html /var/www/html/index.html
